Map<String, String> mapDescription() {
  return {
    "clearsky_day": "Clear sky",
    "clearsky_night": "Clear sky",
    "clearsky_polartwilight": "Clear sky",
    "fair_day": "Fair",
    "fair_night": "Fair",
    "fair_polartwilight": "Fair",
    "partlycloudy_day": "Partly cloudy",
    "partlycloudy_night": "Partly cloudy",
    "partlycloudy_polartwilight": "Partly cloudy",
    "cloudy": "Cloudy",
    "rainshowers_day": "Rain showers",
    "rainshowers_night": "Rain showers",
    "rainshowers_polartwilight": "Rain showers",
    "rainshowersandthunder_day": "Rain showers and thunder",
    "rainshowersandthunder_night": "Rain showers and thunder",
    "rainshowersandthunder_polartwilight": "Rain showers and thunder",
    "sleetshowers_day": "Sleet showers",
    "sleetshowers_night": "Sleet showers",
    "sleetshowers_polartwilight": "Sleet showers",
    "snowshowers_day": "Snow showers",
    "snowshowers_night": "Snow showers",
    "snowshowers_polartwilight": "Snow showers",
    "rain": "Rain",
    "heavyrain": "Heavy rain",
    "heavyrainandthunder": "Heavy rain and thunder",
    "sleet": "Sleet",
    "snow": "Snow",
    "snowandthunder": "Snow and thunder",
    "fog": "Fog",
    "sleetshowersandthunder_day": "Sleet showers and thunder",
    "sleetshowersandthunder_night": "Sleet showers and thunder",
    "sleetshowersandthunder_polartwilight": "Sleet showers and thunder",
    "snowshowersandthunder_day": "Snow showers and thunder",
    "snowshowersandthunder_night": "Snow showers and thunder",
    "snowshowersandthunder_polartwilight": "Snow showers and thunder",
    "rainandthunder": "Rain and thunder",
    "sleetandthunder": "Sleet and thunder",
    "lightrainshowersandthunder_day": "Light rain showers and thunder",
    "lightrainshowersandthunder_night": "Light rain showers and thunder",
    "lightrainshowersandthunder_polartwilight":
        "Light rain showers and thunder",
    "heavyrainshowersandthunder_day": "Heavy rain showers and thunder",
    "heavyrainshowersandthunder_night": "Heavy rain showers and thunder",
    "heavyrainshowersandthunder_polartwilight":
        "Heavy rain showers and thunder",
    "lightssleetshowersandthunder_day": "Light sleet showers and thunder",
    "lightssleetshowersandthunder_night": "Light sleet showers and thunder",
    "lightssleetshowersandthunder_polartwilight":
        "Light sleet showers and thunder",
    "heavysleetshowersandthunder_day": "Heavy sleet showers and thunder",
    "heavysleetshowersandthunder_night": "Heavy sleet showers and thunder",
    "heavysleetshowersandthunder_polartwilight":
        "Heavy sleet showers and thunder",
    "lightssnowshowersandthunder_day": "Light snow showers and thunder",
    "lightssnowshowersandthunder_night": "Light snow showers and thunder",
    "lightssnowshowersandthunder_polartwilight":
        "Light snow showers and thunder",
    "heavysnowshowersandthunder_day": "Heavy snow showers and thunder",
    "heavysnowshowersandthunder_night": "Heavy snow showers and thunder",
    "heavysnowshowersandthunder_polartwilight":
        "Heavy snow showers and thunder",
    "lightrain": "Light rain",
    "lightsleet": "Light sleet",
    "heavysleet": "Heavy sleet",
    "lightsnow": "Light snow",
    "heavysnow": "Heavy snow",
  };
}
